---
name: Hello World

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    name: Hello World job
    runs-on: ubuntu-18.04
    steps:
      - name: Print message
        run: |
          echo "Hello World!"
